import 'package:flutter/material.dart';

class AppLocaleOption {
  final Locale locale;
  final String nativeName;
  final String englishName;

  const AppLocaleOption({
    required this.locale,
    required this.nativeName,
    required this.englishName,
  });
}

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const defaultLocale = Locale('ar');

  static const supportedLocales = <Locale>[
    defaultLocale,
    Locale('en'),
    Locale('hi'),
    Locale('bn'),
    Locale('fr'),
    Locale('es'),
    Locale('it'),
    Locale('fil'),
    Locale('ne'),
    Locale('fa'),
  ];

  static const languageOptions = <AppLocaleOption>[
    AppLocaleOption(
      locale: Locale('ar'),
      nativeName: 'العربية',
      englishName: 'Arabic',
    ),
    AppLocaleOption(
      locale: Locale('en'),
      nativeName: 'English',
      englishName: 'English',
    ),
    AppLocaleOption(
      locale: Locale('hi'),
      nativeName: 'हिन्दी',
      englishName: 'Hindi',
    ),
    AppLocaleOption(
      locale: Locale('bn'),
      nativeName: 'বাংলা',
      englishName: 'Bengali',
    ),
    AppLocaleOption(
      locale: Locale('fr'),
      nativeName: 'Français',
      englishName: 'French',
    ),
    AppLocaleOption(
      locale: Locale('es'),
      nativeName: 'Español',
      englishName: 'Spanish',
    ),
    AppLocaleOption(
      locale: Locale('it'),
      nativeName: 'Italiano',
      englishName: 'Italian',
    ),
    AppLocaleOption(
      locale: Locale('fil'),
      nativeName: 'Filipino',
      englishName: 'Filipino',
    ),
    AppLocaleOption(
      locale: Locale('ne'),
      nativeName: 'नेपाली',
      englishName: 'Nepali',
    ),
    AppLocaleOption(
      locale: Locale('fa'),
      nativeName: 'دری',
      englishName: 'Dari',
    ),
  ];

  static const delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final value = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(value != null, 'AppLocalizations not found in context');
    return value!;
  }

  static bool isRtlLocale(Locale locale) =>
      {'ar', 'fa'}.contains(locale.languageCode);

  String translate(
    String key, {
    String? fallback,
    Map<String, String> params = const {},
  }) {
    final code = locale.languageCode;
    final canonicalKey = _canonicalizeTranslationKey(key);
    final canonicalFallback = fallback == null
        ? null
        : _canonicalizeTranslationKey(fallback);

    final translation =
        _lookupTranslation(code, key) ??
        _lookupTranslation(code, canonicalKey) ??
        _lookupTranslation(code, fallback) ??
        _lookupTranslation(code, canonicalFallback) ??
        (code == 'en'
            ? _lookupTranslation('en', key) ??
                  _lookupTranslation('en', canonicalKey) ??
                  fallback ??
                  key
            : _lookupTranslation('ar', key) ??
                  _lookupTranslation('ar', canonicalKey) ??
                  (_containsArabicScript(canonicalKey)
                      ? canonicalKey
                      : fallback ?? key));

    if (params.isEmpty) return translation;

    var resolved = translation;
    params.forEach((token, value) {
      resolved = resolved.replaceAll('{$token}', value);
    });
    return resolved;
  }
}

extension AppLocalizationContextX on BuildContext {
  String tr(
    String key, {
    String? fallback,
    Map<String, String> params = const {},
  }) {
    return AppLocalizations.of(
      this,
    ).translate(key, fallback: fallback, params: params);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (item) => item.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) {
    return false;
  }
}

const Map<String, Map<String, String>> _translationsByLanguage = {
  'ar': {
    'Media House Edge': 'ميديا هاوس إيدج',
    'Crew / فريق العمل': 'فريق العمل',
    'Category: {category}': 'التصنيف: {category}',
    'Views: {views}': 'المشاهدات: {views}',
    'Preview': 'معاينة',
    'Title': 'العنوان',
    'Description': 'الوصف',
    'Type': 'النوع',
    'Category': 'التصنيف',
    'Upload': 'رفع',
    'Video Cover (Thumbnail)': 'صورة غلاف الفيديو',
    'Folder / Series': 'المجلد / السلسلة',
  },
  'en': {
    'Media House Edge': 'Media House Edge',
    'من نحن': 'About Us',
    'تسجيل الدخول': 'Sign In',
    'إنشاء حساب': 'Create Account',
    'أدخل رمز التحقق': 'Enter Verification Code',
    'تم إرسال رمز التحقق إلى البريد': 'Verification code sent to email',
    'استخدم البريد وكلمة المرور، ثم أكد الرمز من الإيميل':
        'Use email and password, then confirm the code from your email',
    'أرسلنا كود مكون من 6 أرقام إلى {email}':
        'We sent a 6-digit code to {email}',
    'اسم المستخدم': 'Username',
    'البريد الإلكتروني': 'Email',
    'كلمة المرور': 'Password',
    'رمز التحقق': 'Verification Code',
    'تعديل البيانات': 'Edit Details',
    'تأكيد الرمز': 'Confirm Code',
    'إرسال رمز الدخول': 'Send Login Code',
    'إرسال رمز التسجيل': 'Send Registration Code',
    'الدخول كزائر': 'Continue as Guest',
    'ليس لديك حساب؟ إنشاء حساب': 'Don\'t have an account? Create one',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'Already have an account? Sign in',
    'اسم المستخدم لا يقل عن 3 أحرف': 'Username must be at least 3 characters',
    'اكتب بريد صحيح': 'Enter a valid email',
    'كلمة المرور لا تقل عن 6 أحرف': 'Password must be at least 6 characters',
    'اكتب رمز مكون من 6 أرقام': 'Enter a 6-digit code',
    'الحساب': 'Account',
    'تسجيل الخروج': 'Log Out',
    'الدعم الفني': 'Support',
    'اختر طريقة التواصل المناسبة': 'Choose the best contact method',
    'تسجيل رسالة': 'Leave a Message',
    'اكتب طلبك وسيظهر لفريق الدعم':
        'Write your request and it will appear for the support team',
    'التحدث مع خدمة العملاء': 'Talk to Customer Support',
    'المساعد الآلي يرد حتى يستلم الدعم المحادثة':
        'The assistant replies until support joins the conversation',
    'تسجيل رسالة للدعم': 'Leave a Support Message',
    'الاسم': 'Name',
    'اكتب الاسم': 'Enter your name',
    'رسالتك': 'Your Message',
    'اكتب الرسالة': 'Enter your message',
    'إلغاء': 'Cancel',
    'إرسال': 'Send',
    'محادثة خدمة العملاء': 'Support Chat',
    'اكتب رسالتك...': 'Type your message...',
    'تم تسجيل رسالتك للدعم': 'Your support message was recorded',
    'تعذر إرسال الرسالة': 'Unable to send the message',
    'وصلت رسالتك. سأحاول مساعدتك الآن، وتم تحويل المحادثة لفريق خدمة العملاء للرد عليك عند توفر أحدهم.':
        'Your message has been received. I will help now, and the customer support team has been notified to join when available.',
    'خدمات إنتاج سينمائية متكاملة': 'Integrated Cinema Production Services',
    'مسلسلات وافلام , تصوير إعلانات , بودكاست , فديو كليب , إنتاج فني , إنتاج وتوزيع منصات , مونتاج , إخراج سينمائي ':
        'Series and films, ad production, podcasts, music videos, artistic production, platform distribution, editing, and cinematic direction',
    'دعم': 'Support',
    'إخراج': 'Direction',
    'تنفيذ': 'Execution',
    'الحالات الجديده ': 'Latest Stories',
    'لا توجد حالات مضافة الآن': 'No stories added yet',
    'إعلانات': 'Advertisements',
    'اسحب للتصفح': 'Swipe to browse',
    'معرض إعلاني': 'Ad Gallery',
    'خدمات': 'Services',
    'خدمات سينمائية متكاملة': 'Integrated Cinema Services',
    'فريق العمل': 'Team',
    'ملفات تعريف وأعمال أعضاء الفريق':
        'Profiles and portfolios of team members',
    'تعذر تحميل فريق العمل.': 'Unable to load team members.',
    'إعادة المحاولة': 'Retry',
    'أضف أعضاء الفريق من لوحة التحكم ليظهروا هنا.':
        'Add team members from the dashboard to show them here.',
    'خلفيات فيديو': 'Video Backdrops',
    'معاينات متعددة وخفيفة': 'Lightweight multiple previews',
    'مساحة الفيديوهات المتغيرة': 'Dynamic video area',
    'افتح أي عنصر لتشغيله': 'Open any item to play it',
    'فيديو': 'Videos',
    'أضف فيديوهات من لوحة الإدارة لتظهر هنا':
        'Add videos from the dashboard to show them here',
    'أعمال حديثة': 'Recent Work',
    'صور وفيديوهات': 'Photos and videos',
    'معرض الأعمال': 'Portfolio Gallery',
    'أحدث الصور والفيديوهات المضافة.': 'The latest uploaded photos and videos.',
    'عنصر': 'Items',
    'لا توجد أعمال متاحة الآن': 'No work available right now',
    'بيانات الشركة': 'Company Information',
    'السجلات والتواصل': 'Records and Contact',
    'السجل التجاري': 'Commercial Register',
    'الرقم الضريبي': 'Tax Number',
    'العنوان': 'Address',
    'الهاتف': 'Phone',
    'البريد': 'Email',
    'الموقع': 'Website',
    'واتساب': 'WhatsApp',
    'تواصل معنا': 'Contact Us',
    'اكتب طلبك وسنرد عليك': 'Send your request and we will reply',
    'جاري الإرسال': 'Sending...',
    'تم إرسال رسالتك بنجاح': 'Your message was sent successfully',
    'تعذر الإرسال: {error}': 'Unable to send: {error}',
    'تعذر تحديث الإعجاب: {error}': 'Unable to update like: {error}',
    'الكل': 'All',
    'تصوير': 'Filming',
    'مونتاج': 'Editing',
    'إعلانات تجارية': 'Commercial Ads',
    'مسلسلات وافلام': 'Series and Films',
    'تلفزيونية ومنصات': 'Television and streaming platforms',
    'تصوير إعلانات': 'Ad Production',
    'تجارية ودعائية': 'Commercial and promotional',
    'بودكاست': 'Podcasts',
    'برامج صوتية متنوعة': 'Varied audio programs',
    'فديو كليب': 'Music Videos',
    'فيديوهات غنائية': 'Music video productions',
    'إنتاج فني': 'Artistic Production',
    'تصميم وإنتاج عمل فني': 'Design and produce artistic work',
    'إنتاج وتوزيع المنصات': 'Platform Distribution',
    ' بيع وتوزيع وتسويق الاعمال بالمنصات':
        'Sell, distribute, and market productions on platforms',
    'حفلات عالمية': 'Global Events',
    ' تغطية حفلات ومهرجانات عالمية':
        'Coverage for international concerts and festivals',
    'تغطية إعلامية': 'Media Coverage',
    'تغطية إعلامية للأحداث والفعاليات':
        'Media coverage for events and activations',
    'تسجيلات صوتية': 'Audio Recording',
    ' تسجيل صوتي بجودة عالية للاستوديوهات والمنتجين':
        'High-quality voice recording for studios and producers',
    'إعلانات بشراكة حكومية': 'Government Partnership Ads',
    ' إنتاج إعلانات بالتعاون مع جهات حكومية':
        'Produce ads in partnership with government entities',
    'تعاقدات فنانين': 'Artist Contracts',
    'إدارة وحجز وتنسيق التعاقدات الفنية':
        'Manage, book, and coordinate artistic contracts',
    'كواليس التصوير': 'Behind the Scenes',
    'توثيق خلف الكاميرا ولحظات ما وراء المشهد':
        'Behind-the-camera coverage and backstage moments',
    'حجز وإدارة عروض الدي جي والفعاليات الموسيقية':
        'Book and manage DJ sets and music events',
    'أعمال مع مؤسسات دولية': 'International Institution Projects',
    'تنفيذ وإنتاج مشاريع مشتركة مع جهات ومؤسسات دولية':
        'Execute and produce joint projects with international institutions',
    'تعليقات {name}': 'Comments on {name}',
    'مشاهدة': 'Views',
    'النسبة': 'Share',
    'إعجاب': 'Likes',
    'تعليق': 'Comments',
    'التعليقات': 'Comments',
    'اكتب اسمك قبل إرسال التعليق': 'Enter your name before posting a comment',
    'اكتب تعليقك أولًا': 'Write your comment first',
    'تم إرسال التعليق': 'Comment posted',
    'تعذر إرسال التعليق: {error}': 'Unable to post comment: {error}',
    'لا توجد تعليقات حتى الآن': 'No comments yet',
    '{count} تعليق متاح الآن': '{count} comments available now',
    'اسمك الظاهر مع التعليق': 'Displayed name',
    'أضف تعليقًا': 'Add a comment',
    'اكتب رأيك أو ملاحظتك عن عضو الفريق':
        'Write your opinion or note about this team member',
    'جارٍ الإرسال': 'Submitting...',
    'إرسال التعليق': 'Send Comment',
    'ابدأ أول تعليق لهذا العضو.': 'Be the first to comment on this member.',
    'الآن': 'Now',
    'منذ {value} د': '{value}m ago',
    'منذ {value} س': '{value}h ago',
    'منذ {value} يوم': '{value}d ago',
    'أعماله': 'Portfolio',
    'لا توجد أعمال مضافة حاليًا': 'No work added yet',
    '{count} عنصر في المعرض': '{count} items in the gallery',
    'آراء الزوار والمستخدمين على هذا العضو':
        'Visitor and user feedback about this member',
    'أضف رأيك': 'Add Your Feedback',
    'ملف عضو الفريق': 'Team Member Profile',
    '{count} أعمال': '{count} works',
    '{count} مهارات': '{count} skills',
    'تم الإعجاب': 'Liked',
    'عرض التعليقات': 'View Comments',
    'نبذة': 'Overview',
    'المهارات': 'Skills',
    'لا توجد أعمال مضافة لهذا العضو حاليًا.':
        'No work has been added for this member yet.',
    'الوصف': 'Description',
    'تفعيل الصوت': 'Enable Sound',
    'تخطي': 'Skip',
    'تقديم طلب': 'Submit Request',
    'صور': 'Images',
    'لا توجد منشورات لهذه الخدمة حالياً':
        'No posts are available for this service right now',
    'تقديم طلب الخدمة': 'Request This Service',
    'حصل خطأ أثناء تحميل المحتوى': 'An error occurred while loading content',
    'مسلسلات وأفلام': 'Series and Movies',
    'لا توجد عناصر في هذا المجلد': 'No items in this folder',
    'لا يوجد محتوى لهذا الفلتر': 'No content for this filter',
    'الحلقات': 'Episodes',
    'لا توجد مجلدات حالياً': 'No folders available right now',
    '{count} عنصر': '{count} items',
    'Crew / فريق العمل': 'Crew',
    'Category: {category}': 'Category: {category}',
    'Views: {views}': 'Views: {views}',
    'Preview': 'Preview',
    'لوحة التحكم': 'Dashboard',
    'رفع المحتوى': 'Upload Content',
    'الردود': 'Responses',
    'طلبات الخدمات': 'Service Requests',
    'الرئيسية': 'Home',
    'رفع': 'Upload',
    'الفريق': 'Team',
    'الطلبات': 'Requests',
    'Title': 'Title',
    'Description': 'Description',
    'Type': 'Type',
    'Category': 'Category',
    'Upload': 'Upload',
    'Video Cover (Thumbnail)': 'Video Cover (Thumbnail)',
    'Folder / Series': 'Folder / Series',
    'اختر القسم الذي سيظهر للمستخدم': 'Choose the section shown to users',
    'اسم المجلد (اسم المسلسل / الفيلم)': 'Folder name (series / movie name)',
    'اكتب اسم المجلد': 'Enter the folder name',
    'الترتيب داخل المجلد (رقم الحلقة/الجزء)':
        'Order inside the folder (episode / part number)',
    'اكتب رقم صحيح': 'Enter a valid number',
    'سيظهر هذا الرفع في: {title}': 'This upload will appear in: {title}',
    'اختر ملف قبل الرفع': 'Choose a file before uploading',
    'تم رفع المحتوى بنجاح': 'Content uploaded successfully',
    'فشل الرفع: {error}': 'Upload failed: {error}',
    'أضف الموظفين، صورهم، مهاراتهم، وأعمالهم.':
        'Add employees, their photos, skills, and portfolios.',
    'إضافة عضو': 'Add Member',
    'لا يوجد أعضاء فريق مضافون حتى الآن.':
        'No team members have been added yet.',
    'حذف عضو الفريق؟': 'Delete team member?',
    'سيتم حذف "{name}" نهائيًا.': '"{name}" will be deleted permanently.',
    'حذف': 'Delete',
    'تم حذف العضو': 'Member deleted',
    'فشل الحذف: {error}': 'Delete failed: {error}',
    'أدخل عنوان العمل رقم {index}': 'Enter title for work #{index}',
    'اختر ملفًا للعمل "{title}"': 'Choose a file for "{title}"',
    'تم تحديث عضو الفريق': 'Team member updated',
    'تمت إضافة عضو الفريق': 'Team member added',
    'فشل الحفظ: {error}': 'Save failed: {error}',
    'تعديل عضو الفريق': 'Edit Team Member',
    'إضافة عضو فريق': 'Add Team Member',
    'جاري الحفظ...': 'Saving...',
    'حفظ': 'Save',
    'البيانات الأساسية': 'Basic Information',
    'صورة الموظف': 'Employee Photo',
    'المسمى الوظيفي': 'Job Title',
    'اكتب المسمى الوظيفي': 'Enter the job title',
    'نبذة تعريفية': 'Short Bio',
    'المهارات (افصل بينها بفاصلة)': 'Skills (comma separated)',
    'الترتيب': 'Order',
    'الأعمال': 'Portfolio',
    'إضافة عمل': 'Add Work',
    'أضف أعمال الموظف بالصور أو الفيديو.':
        'Add this employee\'s work as images or video.',
    'حفظ البيانات': 'Save Data',
    'ترتيب {value}': 'Order {value}',
    'تعديل': 'Edit',
    'العمل {index}': 'Work {index}',
    'الفيديو': 'Video',
    'الصورة': 'Image',
    'عنوان العمل': 'Work Title',
    'وصف العمل': 'Work Description',
    'نوع الملف': 'File Type',
    'صورة الغلاف': 'Cover Image',
    'اضغط لاختيار ملف': 'Tap to choose a file',
    'حرر الصفحة التعريفية للشركة وأضف أقسامًا وصورًا وفيديوهات.':
        'Edit the company profile page and add sections, images, and videos.',
    'حفظ صفحة من نحن': 'Save About Page',
    'العنوان الرئيسي': 'Main Title',
    'اكتب عنوان الصفحة': 'Enter page title',
    'العنوان الفرعي': 'Subtitle',
    'المقدمة': 'Introduction',
    'الأقسام': 'Sections',
    'إضافة قسم': 'Add Section',
    'أضف أول قسم في صفحة من نحن.': 'Add the first section to the About page.',
    'القسم {index}': 'Section {index}',
    'إضافة وسائط': 'Add Media',
    'عنوان القسم': 'Section Title',
    'المحتوى النصي': 'Text Content',
    'لا توجد وسائط مضافة لهذا القسم.':
        'No media has been added to this section.',
    'عنصر {index}': 'Item {index}',
    'عنوان العنصر': 'Item Title',
    'نوع الوسيط': 'Media Type',
    'لا يوجد محتوى مضاف في صفحة من نحن حتى الآن.':
        'No content has been added to the About page yet.',
    'لغة التطبيق': 'App Language',
    'اختر لغة الواجهة': 'Choose the interface language',
    'المظهر': 'Theme',
    'الوضع الفاتح': 'Light Mode',
    'الوضع الداكن': 'Dark Mode',
    'تلقائي': 'System',
    'عن التطبيق': 'About',
    'الدخول': 'Login',
  },
  'hi': {
    'من نحن': 'हम कौन हैं',
    'تسجيل الدخول': 'साइन इन',
    'إنشاء حساب': 'खाता बनाएँ',
    'أدخل رمز التحقق': 'सत्यापन कोड दर्ज करें',
    'اسم المستخدم': 'उपयोगकर्ता नाम',
    'البريد الإلكتروني': 'ईमेल',
    'كلمة المرور': 'पासवर्ड',
    'رمز التحقق': 'सत्यापन कोड',
    'تعديل البيانات': 'विवरण संपादित करें',
    'تأكيد الرمز': 'कोड पुष्टि करें',
    'إرسال رمز الدخول': 'लॉगिन कोड भेजें',
    'إرسال رمز التسجيل': 'पंजीकरण कोड भेजें',
    'الدخول كزائر': 'अतिथि के रूप में जारी रखें',
    'ليس لديك حساب؟ إنشاء حساب': 'क्या आपके पास खाता नहीं है? खाता बनाएँ',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'क्या आपके पास पहले से खाता है? साइन इन',
    'اكتب بريد صحيح': 'मान्य ईमेल लिखें',
    'الحساب': 'खाता',
    'تسجيل الخروج': 'लॉग आउट',
    'لغة التطبيق': 'ऐप भाषा',
    'اختر لغة الواجهة': 'इंटरफ़ेस भाषा चुनें',
    'المظهر': 'थीम',
    'عن التطبيق': 'ऐप के बारे में',
    'لوحة التحكم': 'डैशबोर्ड',
    'الدخول': 'लॉगिन',
    'الخدمات': 'सेवाएँ',
    'فريق العمل': 'टीम',
    'خلفيات فيديو': 'वीडियो बैकड्रॉप',
    'أعمال حديثة': 'हाल का कार्य',
    'تواصل معنا': 'संपर्क करें',
    'بيانات الشركة': 'कंपनी जानकारी',
    'السجلات والتواصل': 'रिकॉर्ड और संपर्क',
    'الكل': 'सभी',
    'صور': 'चित्र',
    'فيديو': 'वीडियो',
    'إعادة المحاولة': 'पुनः प्रयास करें',
    'تقديم طلب': 'अनुरोध भेजें',
    'تقديم طلب الخدمة': 'सेवा का अनुरोध करें',
    'التعليقات': 'टिप्पणियाँ',
    'مشاهدة': 'दृश्य',
    'إعجاب': 'पसंद',
    'تعليق': 'टिप्पणी',
    'الوصف': 'विवरण',
    'مسلسلات وأفلام': 'सीरीज़ और फ़िल्में',
    'الحلقات': 'एपिसोड',
    'لا توجد مجلدات حالياً': 'अभी कोई फ़ोल्डर उपलब्ध नहीं है',
    'حصل خطأ أثناء تحميل المحتوى': 'सामग्री लोड करते समय त्रुटि हुई',
  },
  'bn': {
    'من نحن': 'আমাদের সম্পর্কে',
    'تسجيل الدخول': 'সাইন ইন',
    'إنشاء حساب': 'অ্যাকাউন্ট তৈরি করুন',
    'أدخل رمز التحقق': 'যাচাইকরণ কোড লিখুন',
    'اسم المستخدم': 'ব্যবহারকারীর নাম',
    'البريد الإلكتروني': 'ইমেইল',
    'كلمة المرور': 'পাসওয়ার্ড',
    'رمز التحقق': 'যাচাইকরণ কোড',
    'تعديل البيانات': 'তথ্য সম্পাদনা করুন',
    'تأكيد الرمز': 'কোড নিশ্চিত করুন',
    'إرسال رمز الدخول': 'লগইন কোড পাঠান',
    'إرسال رمز التسجيل': 'নিবন্ধন কোড পাঠান',
    'الدخول كزائر': 'অতিথি হিসেবে চালিয়ে যান',
    'ليس لديك حساب؟ إنشاء حساب': 'অ্যাকাউন্ট নেই? একটি তৈরি করুন',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন',
    'اكتب بريد صحيح': 'সঠিক ইমেইল লিখুন',
    'الحساب': 'অ্যাকাউন্ট',
    'تسجيل الخروج': 'লগ আউট',
    'لغة التطبيق': 'অ্যাপের ভাষা',
    'اختر لغة الواجهة': 'ইন্টারফেস ভাষা বেছে নিন',
    'المظهر': 'থিম',
    'عن التطبيق': 'অ্যাপ সম্পর্কে',
    'لوحة التحكم': 'ড্যাশবোর্ড',
    'الدخول': 'লগইন',
    'الخدمات': 'সেবা',
    'فريق العمل': 'টিম',
    'خلفيات فيديو': 'ভিডিও ব্যাকড্রপ',
    'أعمال حديثة': 'সাম্প্রতিক কাজ',
    'تواصل معنا': 'যোগাযোগ করুন',
    'بيانات الشركة': 'কোম্পানির তথ্য',
    'السجلات والتواصل': 'রেকর্ড ও যোগাযোগ',
    'الكل': 'সব',
    'صور': 'ছবি',
    'فيديو': 'ভিডিও',
    'إعادة المحاولة': 'আবার চেষ্টা করুন',
    'تقديم طلب': 'অনুরোধ পাঠান',
    'تقديم طلب الخدمة': 'সেবার অনুরোধ করুন',
    'التعليقات': 'মন্তব্য',
    'مشاهدة': 'দেখা',
    'إعجاب': 'লাইক',
    'تعليق': 'মন্তব্য',
    'الوصف': 'বিবরণ',
    'مسلسلات وأفلام': 'সিরিজ ও চলচ্চিত্র',
    'الحلقات': 'পর্বসমূহ',
    'لا توجد مجلدات حالياً': 'এই মুহূর্তে কোনো ফোল্ডার নেই',
    'حصل خطأ أثناء تحميل المحتوى': 'কনটেন্ট লোড করতে গিয়ে সমস্যা হয়েছে',
  },
  'fr': {
    'من نحن': 'À propos',
    'تسجيل الدخول': 'Connexion',
    'إنشاء حساب': 'Créer un compte',
    'أدخل رمز التحقق': 'Saisissez le code de vérification',
    'اسم المستخدم': 'Nom d’utilisateur',
    'البريد الإلكتروني': 'E-mail',
    'كلمة المرور': 'Mot de passe',
    'رمز التحقق': 'Code de vérification',
    'تعديل البيانات': 'Modifier les informations',
    'تأكيد الرمز': 'Confirmer le code',
    'إرسال رمز الدخول': 'Envoyer le code de connexion',
    'إرسال رمز التسجيل': 'Envoyer le code d’inscription',
    'الدخول كزائر': 'Continuer en invité',
    'ليس لديك حساب؟ إنشاء حساب': 'Pas de compte ? Créez-en un',
    'لديك حساب بالفعل؟ تسجيل الدخول':
        'Vous avez déjà un compte ? Connectez-vous',
    'اكتب بريد صحيح': 'Saisissez un e-mail valide',
    'الحساب': 'Compte',
    'تسجيل الخروج': 'Déconnexion',
    'لغة التطبيق': 'Langue de l’application',
    'اختر لغة الواجهة': 'Choisissez la langue de l’interface',
    'المظهر': 'Apparence',
    'عن التطبيق': 'À propos de l’application',
    'لوحة التحكم': 'Tableau de bord',
    'الدخول': 'Connexion',
    'الخدمات': 'Services',
    'فريق العمل': 'Équipe',
    'خلفيات فيديو': 'Arrière-plans vidéo',
    'أعمال حديثة': 'Travaux récents',
    'تواصل معنا': 'Contactez-nous',
    'بيانات الشركة': 'Informations de l’entreprise',
    'السجلات والتواصل': 'Registres et contact',
    'الكل': 'Tout',
    'صور': 'Images',
    'فيديو': 'Vidéos',
    'إعادة المحاولة': 'Réessayer',
    'تقديم طلب': 'Envoyer une demande',
    'تقديم طلب الخدمة': 'Demander ce service',
    'التعليقات': 'Commentaires',
    'مشاهدة': 'Vues',
    'إعجاب': 'J’aime',
    'تعليق': 'Commentaire',
    'الوصف': 'Description',
    'مسلسلات وأفلام': 'Séries et films',
    'الحلقات': 'Épisodes',
    'لا توجد مجلدات حالياً': 'Aucun dossier pour le moment',
    'حصل خطأ أثناء تحميل المحتوى':
        'Une erreur s’est produite lors du chargement du contenu',
  },
  'es': {
    'من نحن': 'Quiénes somos',
    'تسجيل الدخول': 'Iniciar sesión',
    'إنشاء حساب': 'Crear cuenta',
    'أدخل رمز التحقق': 'Introduce el código de verificación',
    'اسم المستخدم': 'Nombre de usuario',
    'البريد الإلكتروني': 'Correo electrónico',
    'كلمة المرور': 'Contraseña',
    'رمز التحقق': 'Código de verificación',
    'تعديل البيانات': 'Editar datos',
    'تأكيد الرمز': 'Confirmar código',
    'إرسال رمز الدخول': 'Enviar código de acceso',
    'إرسال رمز التسجيل': 'Enviar código de registro',
    'الدخول كزائر': 'Continuar como invitado',
    'ليس لديك حساب؟ إنشاء حساب': '¿No tienes cuenta? Crea una',
    'لديك حساب بالفعل؟ تسجيل الدخول': '¿Ya tienes cuenta? Inicia sesión',
    'اكتب بريد صحيح': 'Escribe un correo válido',
    'الحساب': 'Cuenta',
    'تسجيل الخروج': 'Cerrar sesión',
    'لغة التطبيق': 'Idioma de la aplicación',
    'اختر لغة الواجهة': 'Elige el idioma de la interfaz',
    'المظهر': 'Apariencia',
    'عن التطبيق': 'Acerca de la aplicación',
    'لوحة التحكم': 'Panel',
    'الدخول': 'Acceso',
    'الخدمات': 'Servicios',
    'فريق العمل': 'Equipo',
    'خلفيات فيديو': 'Fondos de video',
    'أعمال حديثة': 'Trabajos recientes',
    'تواصل معنا': 'Contáctanos',
    'بيانات الشركة': 'Información de la empresa',
    'السجلات والتواصل': 'Registros y contacto',
    'الكل': 'Todo',
    'صور': 'Imágenes',
    'فيديو': 'Video',
    'إعادة المحاولة': 'Reintentar',
    'تقديم طلب': 'Enviar solicitud',
    'تقديم طلب الخدمة': 'Solicitar este servicio',
    'التعليقات': 'Comentarios',
    'مشاهدة': 'Vistas',
    'إعجاب': 'Me gusta',
    'تعليق': 'Comentario',
    'الوصف': 'Descripción',
    'مسلسلات وأفلام': 'Series y películas',
    'الحلقات': 'Episodios',
    'لا توجد مجلدات حالياً': 'No hay carpetas por ahora',
    'حصل خطأ أثناء تحميل المحتوى': 'Se produjo un error al cargar el contenido',
  },
  'it': {
    'من نحن': 'Chi siamo',
    'تسجيل الدخول': 'Accedi',
    'إنشاء حساب': 'Crea account',
    'أدخل رمز التحقق': 'Inserisci il codice di verifica',
    'اسم المستخدم': 'Nome utente',
    'البريد الإلكتروني': 'E-mail',
    'كلمة المرور': 'Password',
    'رمز التحقق': 'Codice di verifica',
    'تعديل البيانات': 'Modifica dati',
    'تأكيد الرمز': 'Conferma codice',
    'إرسال رمز الدخول': 'Invia codice di accesso',
    'إرسال رمز التسجيل': 'Invia codice di registrazione',
    'الدخول كزائر': 'Continua come ospite',
    'ليس لديك حساب؟ إنشاء حساب': 'Non hai un account? Creane uno',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'Hai già un account? Accedi',
    'اكتب بريد صحيح': 'Inserisci un’e-mail valida',
    'الحساب': 'Account',
    'تسجيل الخروج': 'Esci',
    'لغة التطبيق': 'Lingua dell’app',
    'اختر لغة الواجهة': 'Scegli la lingua dell’interfaccia',
    'المظهر': 'Aspetto',
    'عن التطبيق': 'Informazioni sull’app',
    'لوحة التحكم': 'Dashboard',
    'الدخول': 'Accesso',
    'الخدمات': 'Servizi',
    'فريق العمل': 'Team',
    'خلفيات فيديو': 'Sfondo video',
    'أعمال حديثة': 'Lavori recenti',
    'تواصل معنا': 'Contattaci',
    'بيانات الشركة': 'Informazioni aziendali',
    'السجلات والتواصل': 'Registri e contatti',
    'الكل': 'Tutti',
    'صور': 'Immagini',
    'فيديو': 'Video',
    'إعادة المحاولة': 'Riprova',
    'تقديم طلب': 'Invia richiesta',
    'تقديم طلب الخدمة': 'Richiedi questo servizio',
    'التعليقات': 'Commenti',
    'مشاهدة': 'Visualizzazioni',
    'إعجاب': 'Mi piace',
    'تعليق': 'Commento',
    'الوصف': 'Descrizione',
    'مسلسلات وأفلام': 'Serie e film',
    'الحلقات': 'Episodi',
    'لا توجد مجلدات حالياً': 'Nessuna cartella al momento',
    'حصل خطأ أثناء تحميل المحتوى': 'Si è verificato un errore nel caricamento',
  },
  'fil': {
    'من نحن': 'Tungkol sa Amin',
    'تسجيل الدخول': 'Mag-sign in',
    'إنشاء حساب': 'Gumawa ng account',
    'أدخل رمز التحقق': 'Ilagay ang verification code',
    'اسم المستخدم': 'Username',
    'البريد الإلكتروني': 'Email',
    'كلمة المرور': 'Password',
    'رمز التحقق': 'Verification code',
    'تعديل البيانات': 'I-edit ang detalye',
    'تأكيد الرمز': 'Kumpirmahin ang code',
    'إرسال رمز الدخول': 'Ipadala ang login code',
    'إرسال رمز التسجيل': 'Ipadala ang registration code',
    'الدخول كزائر': 'Magpatuloy bilang bisita',
    'ليس لديك حساب؟ إنشاء حساب': 'Wala ka pang account? Gumawa ng isa',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'May account ka na? Mag-sign in',
    'اكتب بريد صحيح': 'Maglagay ng tamang email',
    'الحساب': 'Account',
    'تسجيل الخروج': 'Mag-log out',
    'لغة التطبيق': 'Wika ng app',
    'اختر لغة الواجهة': 'Piliin ang wika ng interface',
    'المظهر': 'Tema',
    'عن التطبيق': 'Tungkol sa app',
    'لوحة التحكم': 'Dashboard',
    'الدخول': 'Login',
    'الخدمات': 'Mga serbisyo',
    'فريق العمل': 'Team',
    'خلفيات فيديو': 'Video backdrops',
    'أعمال حديثة': 'Mga bagong gawa',
    'تواصل معنا': 'Makipag-ugnayan sa amin',
    'بيانات الشركة': 'Impormasyon ng kumpanya',
    'السجلات والتواصل': 'Mga rekord at contact',
    'الكل': 'Lahat',
    'صور': 'Mga larawan',
    'فيديو': 'Video',
    'إعادة المحاولة': 'Subukan muli',
    'تقديم طلب': 'Magpadala ng request',
    'تقديم طلب الخدمة': 'Humiling ng serbisyong ito',
    'التعليقات': 'Mga komento',
    'مشاهدة': 'Views',
    'إعجاب': 'Like',
    'تعليق': 'Komento',
    'الوصف': 'Paglalarawan',
    'مسلسلات وأفلام': 'Mga serye at pelikula',
    'الحلقات': 'Mga episode',
    'لا توجد مجلدات حالياً': 'Wala pang mga folder sa ngayon',
    'حصل خطأ أثناء تحميل المحتوى': 'Nagkaroon ng error sa pag-load ng content',
  },
  'ne': {
    'من نحن': 'हामीबारे',
    'تسجيل الدخول': 'साइन इन',
    'إنشاء حساب': 'खाता बनाउनुहोस्',
    'أدخل رمز التحقق': 'प्रमाणीकरण कोड प्रविष्ट गर्नुहोस्',
    'اسم المستخدم': 'प्रयोगकर्ता नाम',
    'البريد الإلكتروني': 'इमेल',
    'كلمة المرور': 'पासवर्ड',
    'رمز التحقق': 'प्रमाणीकरण कोड',
    'تعديل البيانات': 'विवरण सम्पादन गर्नुहोस्',
    'تأكيد الرمز': 'कोड पुष्टि गर्नुहोस्',
    'إرسال رمز الدخول': 'लगइन कोड पठाउनुहोस्',
    'إرسال رمز التسجيل': 'दर्ता कोड पठाउनुहोस्',
    'الدخول كزائر': 'अतिथिको रूपमा जारी राख्नुहोस्',
    'ليس لديك حساب؟ إنشاء حساب': 'खाता छैन? एउटा बनाउनुहोस्',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'पहिले नै खाता छ? साइन इन गर्नुहोस्',
    'اكتب بريد صحيح': 'सही इमेल लेख्नुहोस्',
    'الحساب': 'खाता',
    'تسجيل الخروج': 'लगआउट',
    'لغة التطبيق': 'एपको भाषा',
    'اختر لغة الواجهة': 'इन्टरफेसको भाषा छान्नुहोस्',
    'المظهر': 'थिम',
    'عن التطبيق': 'एपबारे',
    'لوحة التحكم': 'ड्यासबोर्ड',
    'الدخول': 'लगइन',
    'الخدمات': 'सेवाहरू',
    'فريق العمل': 'टोली',
    'خلفيات فيديو': 'भिडियो ब्याकड्रप',
    'أعمال حديثة': 'हालसालैका कामहरू',
    'تواصل معنا': 'हामीलाई सम्पर्क गर्नुहोस्',
    'بيانات الشركة': 'कम्पनी जानकारी',
    'السجلات والتواصل': 'रेकर्ड र सम्पर्क',
    'الكل': 'सबै',
    'صور': 'तस्बिरहरू',
    'فيديو': 'भिडियो',
    'إعادة المحاولة': 'पुनः प्रयास गर्नुहोस्',
    'تقديم طلب': 'अनुरोध पठाउनुहोस्',
    'تقديم طلب الخدمة': 'यो सेवा अनुरोध गर्नुहोस्',
    'التعليقات': 'टिप्पणीहरू',
    'مشاهدة': 'हेराइ',
    'إعجاب': 'मनपर्‍यो',
    'تعليق': 'टिप्पणी',
    'الوصف': 'विवरण',
    'مسلسلات وأفلام': 'शृंखला र चलचित्र',
    'الحلقات': 'भागहरू',
    'لا توجد مجلدات حالياً': 'अहिले कुनै फोल्डर छैन',
    'حصل خطأ أثناء تحميل المحتوى': 'सामग्री लोड गर्दा त्रुटि भयो',
  },
  'fa': {
    'من نحن': 'درباره ما',
    'تسجيل الدخول': 'ورود',
    'إنشاء حساب': 'ایجاد حساب',
    'أدخل رمز التحقق': 'کد تایید را وارد کنید',
    'اسم المستخدم': 'نام کاربری',
    'البريد الإلكتروني': 'ایمیل',
    'كلمة المرور': 'رمز عبور',
    'رمز التحقق': 'کد تایید',
    'تعديل البيانات': 'ویرایش اطلاعات',
    'تأكيد الرمز': 'تایید کد',
    'إرسال رمز الدخول': 'ارسال کد ورود',
    'إرسال رمز التسجيل': 'ارسال کد ثبت‌نام',
    'الدخول كزائر': 'ادامه به عنوان مهمان',
    'ليس لديك حساب؟ إنشاء حساب': 'حساب ندارید؟ یک حساب بسازید',
    'لديك حساب بالفعل؟ تسجيل الدخول': 'از قبل حساب دارید؟ وارد شوید',
    'اكتب بريد صحيح': 'ایمیل درست وارد کنید',
    'الحساب': 'حساب',
    'تسجيل الخروج': 'خروج',
    'لغة التطبيق': 'زبان برنامه',
    'اختر لغة الواجهة': 'زبان رابط را انتخاب کنید',
    'المظهر': 'ظاهر',
    'عن التطبيق': 'درباره برنامه',
    'لوحة التحكم': 'داشبورد',
    'الدخول': 'ورود',
    'الخدمات': 'خدمات',
    'فريق العمل': 'تیم',
    'خلفيات فيديو': 'پس‌زمینه‌های ویدیویی',
    'أعمال حديثة': 'کارهای اخیر',
    'تواصل معنا': 'با ما تماس بگیرید',
    'بيانات الشركة': 'اطلاعات شرکت',
    'السجلات والتواصل': 'سوابق و تماس',
    'الكل': 'همه',
    'صور': 'تصاویر',
    'فيديو': 'ویدیو',
    'إعادة المحاولة': 'تلاش دوباره',
    'تقديم طلب': 'ارسال درخواست',
    'تقديم طلب الخدمة': 'درخواست این خدمت',
    'التعليقات': 'نظرها',
    'مشاهدة': 'بازدید',
    'إعجاب': 'پسند',
    'تعليق': 'نظر',
    'الوصف': 'توضیحات',
    'مسلسلات وأفلام': 'سریال‌ها و فیلم‌ها',
    'الحلقات': 'قسمت‌ها',
    'لا توجد مجلدات حالياً': 'در حال حاضر پوشه‌ای وجود ندارد',
    'حصل خطأ أثناء تحميل المحتوى': 'هنگام بارگذاری محتوا خطایی رخ داد',
  },
};

final Map<String, String> _canonicalKeysByEnglishValue = Map.unmodifiable({
  for (final entry in (_translationsByLanguage['en'] ?? const {}).entries)
    entry.value: entry.key,
});

String _canonicalizeTranslationKey(String value) {
  return _canonicalKeysByEnglishValue[value] ?? value;
}

String? _lookupTranslation(String languageCode, String? key) {
  if (key == null || key.isEmpty) return null;
  return _translationsByLanguage[languageCode]?[key];
}

bool _containsArabicScript(String value) {
  return RegExp(r'[\u0600-\u06FF]').hasMatch(value);
}
